spring.application.name=week3.restapi

spring.datasource.url=jdbc:mysql://localhost:3306/charanyadb
spring.datasource.username=root
#TODO - Remove the password before pushing to GIT
spring.datasource.password=Dbcharanya1


# Optional but helpful
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

